### ISSUE TITLE
Connection to binance doesn't close (my assumption)

### ISSUE THREAD

**Issue by Mayhem93** [tiagosiebler/binance#153]
Hello,

So I made a test script just to test out this SDK for the binance API. I'll give you my stripped down code, only including the important bits:

```javascript
let binanceClient = new Binance({
	api_key: apiKey,
	api_secret: apiSecret
});

async function getBinancePrice (ticker) {
	return (await binanceClient.getSymbolPriceTicker({
		symbol: ticker
	})).price;
}

(async () => {
	console.log(await getBinancePrice('BNBUSDT'));
})();
```

This whole code works perfectly, but it hangs, meaning the event loop is still doing something behind, most probably some connections to the Binance API ? How do I close the connections ?

PS: It has something to do with the constructor, I removed the `getBinancePrice` call and the script still hangs.

**Comment by tiagosiebler** [comment]
If you're not using signed requests then I'd definitely just turn it off. It hangs because when this feature is turned on (as it is by default), it spawns and stores an interval timer when you call the constructor (i.e. every x seconds check the delay when sending a request to binance's APIs and receiving a response). As long as that timer is active it would give the assumption that the node process hasn't finished.

**Comment by tiagosiebler** [comment]
Closing this for now. Will re-evaluate in future whether to keep this time sync mechanism enabled by default.

**Comment by felds** [comment]
@tiagosiebler browsing through the code, it looks like the execution get stuck because of [this line](https://github.com/tiagosiebler/binance/blob/1bb97da90aba5c5555a1d6298f0a0b0caf950134/src/util/BaseRestClient.ts#L78).

As long there are any `setInterval` of `setTimeout` waiting, node won't end the execution. I previously had success just getting the offset once and using the same offset for all other requests. Maybe we could do the same?

@Mayhem93 I fixed the problem in my code by disabling auto sync and syncing the time once, after creating the client:
```ts
const asyncClient = new Promise(async () => {
  const client = new MainClient({
    api_key: API_KEY,
    api_secret: API_SECRET,
    disableTimeSync: true,
  })
  await client.syncTime()
  return client
})
```

Whenever I want to use this client, I just unwrap the promise:
```ts
const client = await asyncClient
const response = await client.doSomething();
```

**Comment by tiagosiebler** [comment]
> @tiagosiebler browsing through the code, it looks like the execution gets stuck because of [this line](https://github.com/tiagosiebler/binance/blob/1bb97da90aba5c5555a1d6298f0a0b0caf950134/src/util/BaseRestClient.ts#L78).
> 
> As long there are any `setInterval` of `setTimeout` waiting, node won't end the execution. I previously had success just getting the offset once and using the same offset for all other requests. Maybe we could do the same?

Yes, it's the running timer from the time-sync feature that's typically preventing exit after you've finished making API calls. You actually don't need to get an offset, technically the feature is optional (that's also why it can be turned off easily).

I'm most likely going to disable it by default in the next release (in all my connectors) as I do think it's causing more problems for most people than it solves (from recv window errors to frequent questions on why the process doesn't exit). I'll still keep it in the connector so it can be turned on if needed, but it'll be off by default.

**Comment by felds** [comment]
I think the default behavior is okay, since not every system use the same reference time (google has [leap smear](https://developers.google.com/time/smear) for example) and it's a nice failsafe. In my mac, the API doesn't work until I add the offset.

My only objection is the timeout. Once the offset is stablished, there's no much drift, and calling `syncTime` is not much to ask for someone running a long-lived process.
