### ISSUE TITLE
Prefixed order IDs

### ISSUE THREAD

**Issue by A-ndy-git** [tiagosiebler/binance#166]
What is the purpose of requiring custom prefixes for clientOrderIds?

On SPOT it requires `x-U5D79M5B`. While not a massive issue, it would be interesting to understand the reasoning behind this design.

Also, it appears the `generateNewOrderId()` is not accessible via any clients. Is this something we can make available to the MainClient?

**Comment by tiagosiebler** [comment]
Hi @A-ndy-git 

Glad to clarify why I've added this requirement. Over the years in working with them I've established a relationship with binance - a light but not insignificant one. They're familiar of this connector & my work on it (and in some cases support it on telegram - or at least state it's one of the popular public connectors for nodejs devs). 

These order ID prefixes essentially allow binance to define a relationship between volume traded with these prefixes, with the connector itself. 

In other words all orders prefixed with this uuid are from platforms benefitting from this community connector alone. This adds more weight to the popularity of this connector, and in turn adds weight in the rare case I do communicate with their engineering team (for example if something important on their end starts to misbehave or worse, or we simply require clarification in a situation such as #162 where the answer is not easy to determine independently). 

More volume means they see a bigger impact in addressing queries or issues raised through me. Situations that impact a larger audience typically receive higher priority than individual problems, unfortunately. It does also bring other advantages such as my ability to request sub-account activation for "my users" - something I can do for anyone interested (drop me a message on telegram if that is the case). So in short, it's a very passive way to thank me for my work (when I talk to binance about anything technical) and it helps enable some community-benefitting "powers". 

I would've loved a less intrusive way to define that association instead of forcing order ID prefixing, but sadly they were not able to provide one. The prefix is also slightly different if you happen to trade futures instead of spot markets.

Regarding the latter comment, I did mean to expose those as exported methods in the case that one wanted to pre-generate an order ID before actually submitting an order. It's a mistake if they're not accessible and I'd welcome a PR to address that. 

In the case the current implementation of `generateNewOrderId` is not unique enough, I'd also welcome ideas to improve the randomness of it to reduce the chance of order ID collisions (a very rare situation for significantly higher volume accounts).

**Comment by A-ndy-git** [comment]
Hi @tiagosiebler,

Thanks for sharing the above information. Helps to clear up the reasoning behind the implementation. 

I seem to encounter many random issues with orders utilising this method. When I enter a position the order is prefixed with `U5D79M5B_`, one strategy then places an OCO order, and prefixes it with `x-U5D79M5B_SL-` or `x-U5D79M5B_SL-`.

I would imagine this is a very common method, but it leaves my code with an undesirable amount of replace functions just trying to revert the orderId to the format I want to see it in.

This subsequently creates so many random, hard to troubleshoot errors, like this:

```
{
limitClientOrderId: 'x-U5D79M5B_TP-x-U5D79M5B_t-c93EL8oaomOQ6FuD_F2'
...some_additional_properties_here
}
```

Randomly returns an error:

```
{
    code: -1100,
    msg: "Illegal characters found in parameter 'limitClientOrderId'; legal range is '^[a-zA-Z0-9-_]{1,36}$'."
 }
```

While the reasoning makes complete sense and it would be logical to continue this method - there has to be a better way we can implement this. Perhaps the `MainClient` could prefix & un-prefix these orders automatically without the user's knowledge? 

Just suggestions - I understand if its not something you think would benefit the wider package.

**Comment by tiagosiebler** [comment]
That's interesting and certainly unexpected/unintended. Thank you for raising it. 

The logic shouldn't be adding a prefix to an existing order ID - it would only complain about the lack of prefix if one wasn't provided. Have you determined why the prefix is repeated like this? Or is this a side-effect of how your engine tracks orders using some metadata in the order ID? 

There's unfortunately very limited space in how many characters you can fit into the custom order ID, due to the validation limitation on binance's API. So I would also generally discourage trying to store any state in a custom order ID. 

Instead, I would:
- Pre-generate your own unique ID (with the prefix) and use it as a primary key.
- Store any context relating to your order (e.g `orderType: 'TP'`) in a map (or any other form of key:value store).
- Submit the order.

Then, once the order is processed and events start coming in, you can always query context from your key-store as soon as you need it, using the order ID you prepared before submitting the request.

While in some ways I do like your idea to prefix & un-prefix predefined order IDs on the fly, I do have some concerns that lead me to believe it's not viable in the scenario where the caller provides a custom order ID in the function call:
- What if the provided ID is already too long? E.g `uuidv4`, a common standard nowadays. I guess we could throw a warning like now and avoid handling it automatically.
- What if the order is already correctly prefixed? I guess some temporary state could track this during execution, dictating whether the the response should be un-prefixed.
- What if the implementation tracks order events asynchronously (e.g via the ws), and uses a key-store as I suggested above? Those async orders would no longer match anything known to the implementation, making any integration of the connector more painful than it should be...

Hope this helps. If you have any questions or thoughts, let me know!

**Comment by A-ndy-git** [comment]
Thank you for the detail @tiagosiebler. This is a very basic strategy built in the below format:

1) The strategy receives a signal and creates a `MARKET` buy order. The order has a `newClientOrderId` prefixed with `x-U5D79M5B`
2) Once the `MARKET` order is filled, an OCO order is created.*

* Here is where the complexity is introduced. Lets say the first market order's ID is `U5D79M5B-ORDER-1`, and we store this in the db. Once we need to place the second market OCO, we have to specify both a `limitClientOrderId` and a `stopClientOrderId`.

While it is frustrating, from reading your comments, I do agree the value gained from keeping prefixes far outweighs the additional dev work required.

I will architect my design around this - thanks very much for your help. It is greatly appreciated.
