### ISSUE TITLE
[Bug] - Warning + cancelOrder

### ISSUE THREAD

**Issue by itsbeeut** [tiagosiebler/binance#187]
Hi thanks for this amazing job,
There are two problems,
1- based on https://binance-docs.github.io/apidocs/futures/en/#new-order-trade,
newClientOrderId should follow: `^[\.A-Z\:/a-z0-9_-]{1,36}$`
so this warning is kind of wrong
```
WARNING: 'newClientOrderId' invalid - it should be prefixed with x-15PC4ZJy. Use the 'client.generateNewOrderId()' REST client utility method to generate a fresh order ID on demand.
```

2- based on https://binance-docs.github.io/apidocs/futures/en/#cancel-order-trade,
this method parameters are wrong, `client.cancelOrder({ })`
you dont need these two
```
isIsolated,
newClientOrderId
```

Again thanks a lot 🥰

**Comment by tiagosiebler** [comment]
Hi @itsbeeut - glad you're enjoying my connector. The first point is intentional - you can read why I've made this a requirement, here: #166. I recommend making use of `generateNewOrderId()` if you wish to automatically generate a new order ID to include with your request, while you're still preparing other parameters. Or build your own logic to include the prefix for futures orders.

Regarding the 2nd point, @A-ndy-git was `isIsolated` from your addition? Perhaps we need separate request type interfaces for margin vs others, if margin has params that don't exist for others. Seems `newClientOrderId` is used by spot & margin but not futures.

@itsbeeut these two parameters are optional, so you can just ignore them if you're not using them. We'll clean this up in future (although a PR is welcome if you're happy to enhance the type definitions).

**Comment by itsbeeut** [comment]
@tiagosiebler thanks for the replay,
Also i found more things,

1- https://binance-docs.github.io/apidocs/spot/en/#new-future-account-transfer-user_data
`MainClient` doesn't provide this (its available in universal)
i guess we should use `postPrivate`

2- https://binance-docs.github.io/apidocs/futures/en/#new-order-trade
submitNewOrder does not have type `STOP_MARKET` and `TAKE_PROFIT_MARKET`
```
client.submitNewOrder({
    type: "STOP_MARKET"
})
```
🥰

**Comment by tiagosiebler** [comment]
> @tiagosiebler thanks for the replay, Also i found more things,
> 
> 1- https://binance-docs.github.io/apidocs/spot/en/#new-future-account-transfer-user_data `MainClient` doesn't provide this (its available in universal) i guess we should use `postPrivate`

While I've tried to integrate as many endpoints as I could, some are still missing. There's two universal transfer endpoints in place but it seems like the ones you've mentioned haven't been added yet. Would you be interested in making a pull request? There's similar methods already, you could adapt them to add the missing ones you're interested in. Examples:
https://github.com/tiagosiebler/binance/blob/master/src/main-client.ts#L175-L181

If you have any questions, let me know!

> 2- https://binance-docs.github.io/apidocs/futures/en/#new-order-trade submitNewOrder does not have type `STOP_MARKET` and `TAKE_PROFIT_MARKET`
> 
> ```
> client.submitNewOrder({
>     type: "STOP_MARKET"
> })
> ```

You're right! Seems like a mistake because those extra types already exist on `FuturesOrderType` but `NewFuturesOrderParams` is using `OrderType` instead:
https://github.com/tiagosiebler/binance/blob/5bb6e5ea5622089e3c867d671ef7bfca6cb1ccc2/src/types/futures.ts#L75

Should be a quick change to change:
```
export interface NewFuturesOrderParams {
  symbol: string;
  side: OrderSide;
  positionSide?: PositionSide;
  type: OrderType;
```

to
```
export interface NewFuturesOrderParams {
  symbol: string;
  side: OrderSide;
  positionSide?: PositionSide;
  type: FuturesOrderType;
```

**Comment by A-ndy-git** [comment]
Hi @tiagosiebler , @itsbeeut ,

Yes, `isIsolated` was my addition however `newClientOrderId` was already existing on this type. I was not aware that futures were utilising these shared types. As mentioned, they are optional and can safely be ignored when working on futures.

**Comment by tiagosiebler** [comment]
The futures order type param will be fixed in the next release.
