### ISSUE TITLE
Get margin position for USDT

### ISSUE THREAD

**Issue by guyappy** [tiagosiebler/binance#262]
Hi,

I'm having trouble finding the right function. I'm trying to get the current position data for margin, specifically USDT. Is there already a function available for that in the binance connector? 

![image](https://user-images.githubusercontent.com/15813315/203075321-9c750ebc-400e-4a8c-9f3d-46fb4d89c84b.png)

thank you and kind regards,
Guy

**Comment by tiagosiebler** [comment]
This is definitely "margin", not "USDM Futures" right?

Do you see any APIs in the API docs with the data you're looking for?
https://binance-docs.github.io/apidocs/spot/en/#margin-account-trade

USDM futures has a positions endpoint:
https://binance-docs.github.io/apidocs/futures/en/#position-information-v2-user_data

This is exposed via the USDM Client via getPositions(): https://github.com/tiagosiebler/binance/blob/master/src/usdm-client.ts#L342

I can't find anything like this in the official api docs, but I've asked in the binance API telegram group: https://t.me/binance_api_english/303893

**Comment by guyappy** [comment]
thank you for the quick reply!

Indeed, this is definitely margin, not USDM. 

I can't find any API for this in the docs. Strange that it might not even exist? 

Thanks a million for asking this in the telegram!

**Comment by tiagosiebler** [comment]
Seems like it doesn't exist...really weird, given the website has this info presented as positions... hopefully I'll get a comment in the telegram group.

**Comment by tiagosiebler** [comment]
Hi @guyappy 

Response from binance:
> in spot margin UI, the Position is about the funds available in your cross margin wallet of that asset. So you should be able to query by endpoint, {{url}}/sapi/v1/margin/account

This endpoint is available via `queryCrossMarginAccountDetails()` in the main client:
https://github.com/tiagosiebler/binance/blob/master/src/main-client.ts#L884

I thought/assumed this "position" column meant the position average price, because in USDM futures this is what position means, but seems like it actually means "quantity" in spot margin. Can you check if this matches the values you're looking for?
