### ISSUE TITLE
Fills notifications for Limit orders?

### ISSUE THREAD

**Issue by jule64** [tiagosiebler/binance#269]
Hi Tiago, 

I was wondering what is the right way to check when a limit order gets executed with your connectors?  Is there a notification functionality for it or if not what would the standard pattern?  

With your FTX connectors we could simply subscribe to the ws fills channel which was neat (too bad that we can't use that anymore :( 

Note I wasn't sure if this was a question for your "awesome crypto examples" project but happy to post it there if preferred.

Thanks
Julien

**Comment by tiagosiebler** [comment]
Hi @jule64 

Also sad about FTX :( 

Yes, with binance all account events are on one websocket topic. Binance calls it the "user data" stream. There's one user data stream per binance section (e.g. spot vs cross margin vs isolated margin vs usdm futures vs coinm futures).

There's an example here on how to subscribe to those with the websocket client in the binance connector:
https://github.com/tiagosiebler/binance/blob/master/examples/ws-userdata.ts#L75

If you instance the ws client using the `beautify:true` property (like this sample does), you can listen to `formattedMessage` events from the ws client. You can even use the type guard `isWsFormattedUserDataEvent(event)` (included in the package) to catch use data events and narrow down the type (especially useful if you're using typescript):
https://github.com/tiagosiebler/binance/blob/master/examples/ws-userdata.ts#L74

From there on, take a look at the events being logged by this line when you see a limit order fill. The event can vary depending on the type of action (e.g. order fill will have a different event compared to a transfer from spot to futures). 

I've added a few extra type guards to detect a bit more about the type of user data event:
https://github.com/tiagosiebler/binance/blob/master/examples/ws-userdata.ts#L35-L65

There's a lot of types too in spot vs futures events, but if you have more type guards that would help you I'd welcome a PR:
https://github.com/tiagosiebler/binance/blob/master/src/types/websockets.ts#L34-L59

There's probably also a few types that are still missing, which I'd absolutely welcome as an addition via a PR.

> Note I wasn't sure if this was a question for your "awesome crypto examples" project but happy to post it there if preferred.

Since this is more specific to usage of the binance connector, this feels the right place to ask this 🙂 hope this connector helps your binance implementation. In some ways, it's a stronger connector with all the work on adding types for ws events and REST requests & replies, as well as the type guards and the beautifier for ws events. So hopefully the integration is even easier than the one with FTX was.

**Comment by jule64** [comment]
Ok great!  I didn't realise that's what the "user data" stream was for but now that makes sense!  Going to try that out now.

Thanks also for the extra info and examples.  I am not using the TS types yet but going to as I can see that's definitely going to help my implementation.

Question resolved, thanks again!

**Comment by tiagosiebler** [comment]
>  I am not using the TS types yet but going to as I can see that's definitely going to help my implementation.

Deffo recommend it, it'll make your journey much easier after (max) a week of adoption. Especially since the connectors have a ton of types implemented (requests, responses and websockets).

Here's a quick start intro to typescript I saw & shared recently in the telegram group: https://www.robinwieruch.de/typescript-node/

**Comment by jule64** [comment]
Thanks for the TS tutorial, looks good 👌
