### ISSUE TITLE
Margin Accountbug simple suggested fix

### ISSUE THREAD

**Issue by TomToms55** [tiagosiebler/binance#285]
Missing parenthesis in line 4813 function _mgAccount_.  

```js
endpoint += (isIsolated)?'/isolated':'' + '/account';
```
to

```js
endpoint += ((isIsolated)?'/isolated':'') + '/account';
```

Context (corrected):

```js
/**
 * Margin account details
 * @param {function} callback - the callback function
 * @param {boolean} isIsolated - the callback function
 * @return {undefined}
 */
mgAccount: function( callback ,isIsolated = false) {
    let endpoint = 'v1/margin';
    endpoint += ((isIsolated)?'/isolated':'') + '/account';
    signedRequest( sapi + endpoint, {}, function( error, data ) {
        if( callback ) return callback( error, data );
    } );
},
```

**Comment by tiagosiebler** [comment]
Hi @TomToms55 ,

I think you may be referring to a different SDK. My connectors all use promises instead of callbacks, and this particular pair of endpoints is exposed as two separate functions in the `MainClient` class:
https://github.com/tiagosiebler/binance/blob/master/src/main-client.ts#L910
https://github.com/tiagosiebler/binance/blob/master/src/main-client.ts#L970

**Comment by TomToms55** [comment]
Your are right! Sorry about that. Too many tabs opened. I wanted to comment on node-binance-api. Your SDK is fully functional :)
Have a great day
