### ISSUE TITLE
Missing Wallet endpoints

### ISSUE THREAD

**Issue by emiliocr90** [tiagosiebler/binance#315]
Please add the missing main client's wallet endpoints. For example, https://binance-docs.github.io/apidocs/spot/en/#user-asset-user_data

**Comment by tiagosiebler** [comment]
Thanks for raising this. I'm looking to work towards full API coverage, including thorough types as well as end to end tests. This has been an incremental progress, in all my SDKs. If you're looking for these missing pieces sooner rather than later, I'd also absolutely welcome contributions via pull requests.

**Comment by JJ-Cro** [comment]
All rest endpoints are now added as of recently, in case you are still looking for it.
