### ISSUE TITLE
Module not found: Can't resolve 'socks-proxy-agent'

### ISSUE THREAD

**Issue by liho00** [tiagosiebler/binance#395]
Getting error `Module not found: Can't resolve 'socks-proxy-agent'` when running the code below, in next js browser.

```
const { USDMClient: _BinanceUSDMClient } = require("binance");
export const USDMClient = new _BinanceUSDMClient({
  api_key: API_KEY,
  api_secret: API_SECRET,
  baseUrl:
    typeof window === "undefined"
      ? "https://testnet.binancefuture.com"
      : "/proxy",
});
```

<img width="1195" alt="image" src="https://github.com/tiagosiebler/binance/assets/77238199/4a43628b-3f5a-4bce-b5f8-2314d0d05a69">

**Comment by tiagosiebler** [comment]
The SDK exports these two utility methods as a convenience, but they're not actually used by the SDK. There only there if someone needs them, so these dependencies are optional:
https://github.com/tiagosiebler/binance/blob/master/src/util/proxy.ts

I'm not sure why your build step is automatically trying to resolve that import for "socks-proxy-agent" since you're not using that function directly, perhaps this is a nextjs thing? Maybe there's a way to tell nextjs that any import/require calls for "socks-proxy-agent" should return undefined? Would love to know if you find a way past this.

**Comment by liho00** [comment]
```
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,

  webpack: (config, { isServer }) => {
    if (!isServer) {
      config.resolve.fallback = {
        fs: false,
      };
    }

    return config;
  },
};

module.exports = nextConfig;

```

not sure its a good idea to doing so, but this is the way i bypass this issue currently.

reference: https://sentry.io/answers/module-not-found-nextjs/#:~:text=This%20error%20usually%20occurs%20when,had%20tried%20to%20access%20it.
